[package]
name = "midi-strip-client"
version = "0.1.0"
authors = ["prior"]

[dependencies]
midir = "0.5.0"
hsl = "0.1.1"
clap = { features = ["yaml"], version = "2.32.0" }
ws = "0.7.8"
serde_derive = "1.0.79"
serde = "1.0.79"
serde_json = "1.0.31"
